
- setup: true
- run: |
    apt-get update && \
    apt-get install -y curl gnupg wget unzip && \
    curl -sSL https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o chrome.deb && \
    apt-get update && \
    apt-get install ./chrome.deb -y --no-install-recommends && \
    rm chrome.deb && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    google-chrome --version
- run: |
    apt-get purge -y curl gnupg wget unzip && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

