# Generated by Django 3.2.17 on 2023-02-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulkapp', '0002_auto_20230222_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmatsaccount',
            name='crn',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='dmatsaccount',
            name='username',
            field=models.IntegerField(error_messages={'unique': 'A user with that db id already exists.'}, unique=True),
        ),
    ]
